from .knn import Knn
from .persistence import Persistence
from .xlstm import xLstm
from .lstm import Lstm
from .transformer import Transformer
from .transformer_full import TransformerFull
from .perfect import Perfect
from .gam import Gam
from .normalizer import Normalizer
from .physics_pv_forecast import PhysicsPvForecast
from .ridge import Ridge
from .random_forest import RandomForest
from .xgb import XGBoost