name: Smoke Test

on:
# push:
#   branches:
#     - main
# pull_request:
#   branches:
#     - main

jobs:
  smoketest:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup disk space
        run:
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
    
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: envs/env_linux.yml
          activate-environment: xlstm

      # Step 3: Run Smoke Tests
      - name: Run Smoke Tests
        run: python tests/smoke_test.py
